version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: your_app_key
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: prestige_watches_store
      DB_USERNAME: prestige_watches_store_user
      DB_PASSWORD: 0BLrgr6TU9iBJNE1LIWVIE7PpWrP9BRK
    volumes:
      - .:/var/www/html

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: prestige_watches_store
      POSTGRES_USER: prestige_watches_store_user
      POSTGRES_PASSWORD: 0BLrgr6TU9iBJNE1LIWVIE7PpWrP9BRK
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
