<?php

namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class Home extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $features = [
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris2.png',
                'alt' => 'Daytona Cosmographe gris 116518LN',
                'title' => 'Daytona Cosmographe gris 116518LN',
                'images' => [
                    "assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris2.png",
                    "assets/img/rolex/Daytona Cosmographe gris 116518LN/r13.jpg",
                    "assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris5.png",
                    "assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris1.png",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/datejust fond vert 41mm/3_126300-green-jub-126300-0020-3-510x680.webp',
                'alt' => 'datejust fond vert 41mm',
                'title' => 'datejust fond vert 41mm',
                'images' => [
                    "assets/img/rolex/datejust fond vert 41mm/3_126300-green-jub-126300-0020-3-510x680.webp",
                    "assets/img/rolex/datejust fond vert 41mm/4_126300-green-jub-126300-0020-2-510x680.webp",
                    "assets/img/rolex/datejust fond vert 41mm/5_BASELUXMMOMENT_2.jpg",
                    "assets/img/rolex/datejust fond vert 41mm/1_126300-green-jub-126300-0020-5-510x680.webp",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Milgauss Fond Bleu 116400GV/4_milgaussblue4.jpg',
                'alt' => 'Milgauss Fond Bleu 116400GV',
                'title' => 'Milgauss Fond Bleu 116400GV',
                'images' => [
                    "assets/img/rolex/Milgauss Fond Bleu 116400GV/4_milgaussblue4.jpg",
                    "assets/img/rolex/Milgauss Fond Bleu 116400GV/2_milgaussblue1.jpg",
                    "assets/img/rolex/Milgauss Fond Bleu 116400GV/1_milgaussblue2.jpg",
                    "assets/img/rolex/Milgauss Fond Bleu 116400GV/5_milgaussblue2.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ]
        ];

        $product = [
            'tag' => 'Sale',
            'image' => 'assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris2.png',
            'alt' => 'Daytona Cosmographe gris 116518LN',
            'title' => 'Daytona Cosmographe gris 116518LN',
            'images' => [
                "assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris2.png",
                "assets/img/rolex/Daytona Cosmographe gris 116518LN/r13.jpg",
                "assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris5.png",
                "assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris1.png",
            ],
            'slug' => 'rolex',
            'brand_slug' => 'rolex',
            'price' => '750',
            'price_packaging' => '900',
        ];

        $products = [
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/Audemars Piguet Royal Oak/2_ap5_55aad9ca-1c41-4c2b-bea0-4149db28a709.jpg',
                'alt' => 'Audemars Piguet Royal Oak',
                'title' => 'Audemars Piguet Royal Oak',
                'images' => [
                    "assets/img/audemars/Audemars Piguet Royal Oak/2_ap5_55aad9ca-1c41-4c2b-bea0-4149db28a709.jpg",
                    "assets/img/audemars/Audemars Piguet Royal Oak/4_BASELUXREF_45.png",
                    "assets/img/audemars/Audemars Piguet Royal Oak/1_ap4_10358e30-d297-4d36-be19-c15cd6cd0e73.jpg",
                    "assets/img/audemars/Audemars Piguet Royal Oak/3_ap3.jpg",
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/Audemars Royal Oak Fond Blanc 41mm Homme/3_ap4_a82162a6-8bcb-43f7-bb5a-09726aaf6057.jpg',
                'alt' => 'Audemars Royal Oak Fond Blanc 41mm Homme',
                'title' => 'Audemars Royal Oak Fond Blanc 41mm Homme',
                'images' => [
                    "assets/img/audemars/Audemars Royal Oak Fond Blanc 41mm Homme/3_ap4_a82162a6-8bcb-43f7-bb5a-09726aaf6057.jpg",
                    "assets/img/audemars/Audemars Royal Oak Fond Blanc 41mm Homme/2_ap4_a82162a6-8bcb-43f7-bb5a-09726aaf6057.jpg",
                    "assets/img/audemars/Audemars Royal Oak Fond Blanc 41mm Homme/1_apwhite2.jpg",
                    "assets/img/audemars/Audemars Royal Oak Fond Blanc 41mm Homme/4_ap5_8ad7e66b-9fe2-4354-b5d3-1bf7f546aa1d.jpg",
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/Audemars Offshore Diver Chronographe 44 mm Jaune/1_Lady_Dior_My_ABC_27.png',
                'alt' => 'Audemars Offshore Diver Chronographe 44 mm Jaune',
                'title' => 'Audemars Offshore Diver Chronographe 44 mm Jaune',
                'images' => [
                    "assets/img/audemars/Audemars Offshore Diver Chronographe 44 mm Jaune/1_Lady_Dior_My_ABC_27.png",
                    "assets/img/audemars/Audemars Offshore Diver Chronographe 44 mm Jaune/3_photo1632404285.jpg",
                    "assets/img/audemars/Audemars Offshore Diver Chronographe 44 mm Jaune/5_audemarsjaune1.jpg",
                    "assets/img/audemars/Audemars Offshore Diver Chronographe 44 mm Jaune/4_audemarsjaune.jpg",
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/Audemars Piguet Royal Oak Skeleton argenté/4_image_1200x_d9cb8a2e-ac4c-4990-af0f-fa3e7c6568eb.jpg',
                'alt' => 'Audemars Piguet Royal Oak Skeleton argenté',
                'title' => 'Audemars Piguet Royal Oak Skeleton argenté',
                'images' => [
                    "assets/img/audemars/Audemars Piguet Royal Oak Skeleton argenté/4_image_1200x_d9cb8a2e-ac4c-4990-af0f-fa3e7c6568eb.jpg",
                    "assets/img/audemars/Audemars Piguet Royal Oak Skeleton argenté/1_image_1200x_95ef0cd8-23fe-44fe-ab1c-804894e77e56.jpg",
                    "assets/img/audemars/Audemars Piguet Royal Oak Skeleton argenté/2_image_1200x_abceb3a8-4f20-41f2-8bd6-1dd25224143c.jpg",
                    "assets/img/audemars/Audemars Piguet Royal Oak Skeleton argenté/3_image_1200x_6c7c777b-dbdd-4075-9f33-7128a1bd66ac.jpg",
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/Audemars piguet chronographe noir/4_Audemars-Piguet-26320ST.OO_.1220ST.01-Royal-Oak-Cronograph-Full-Set-Passione-Vintage-Palermo0A-7-scaled.jpg',
                'alt' => 'Audemars piguet chronographe noir',
                'title' => 'Audemars piguet chronographe noir',
                'images' => [
                    "assets/img/audemars/Audemars piguet chronographe noir/4_Audemars-Piguet-26320ST.OO_.1220ST.01-Royal-Oak-Cronograph-Full-Set-Passione-Vintage-Palermo0A-7-scaled.jpg",
                    "assets/img/audemars/Audemars piguet chronographe noir/1_watch-club-audemars-piguet-royal-oak-box-and-papers-never-polished-ref-26320stoo1220st01-year-2014-wb.jpgwbwbwbwbwb8.jpg",
                    "assets/img/audemars/Audemars piguet chronographe noir/3_26576317-pvfs5utrr52ndgdgcchvrzbw-ExtraLarge.webp",
                    "assets/img/audemars/Audemars piguet chronographe noir/2_1_80a89a84-b27c-4f90-a26d-4850a520b8a4.png",
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/Audemars Piguet Royal Oak rose gold/5_image_23f37430-d809-41a9-b323-baa185478b86.jpg',
                'alt' => 'Audemars Piguet Royal Oak rose gold',
                'title' => 'Audemars Piguet Royal Oak rose gold',
                'images' => [
                    "assets/img/audemars/Audemars Piguet Royal Oak rose gold/5_image_23f37430-d809-41a9-b323-baa185478b86.jpg",
                    "assets/img/audemars/Audemars Piguet Royal Oak rose gold/3_image_c05bd2fe-f2a0-42d4-881a-7ca6111f17f3.jpg",
                    "assets/img/audemars/Audemars Piguet Royal Oak rose gold/2_image_a4584039-5d7b-4fce-9395-266d40d91ec1.jpg",
                    "assets/img/audemars/Audemars Piguet Royal Oak rose gold/1_BASELUXREF_97190428-d13f-4dc9-8338-8a0bc569bb7a.jpg",
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/Audemars Offshore Diver 44 mm Vert/3_photo1664037810_7.jpg',
                'alt' => 'Audemars Offshore Diver 44 mm Vert',
                'title' => 'Audemars Offshore Diver 44 mm Vert',
                'images' => [
                    "assets/img/audemars/Audemars Offshore Diver 44 mm Vert/3_photo1664037810_7.jpg",
                    "assets/img/audemars/Audemars Offshore Diver 44 mm Vert/4_photo1664037810_7.jpg",
                    "assets/img/audemars/Audemars Offshore Diver 44 mm Vert/2_photo1664037810_5.jpg",
                    "assets/img/audemars/Audemars Offshore Diver 44 mm Vert/1_photo1664037810_8.jpg",
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/Audemars Royal Oak Fond Noir 41mm Homme/5_apnoir2.png',
                'alt' => 'Audemars Royal Oak Fond Noir 41mm Homme',
                'title' => 'Audemars Royal Oak Fond Noir 41mm Homme',
                'images' => [
                    "assets/img/audemars/Audemars Royal Oak Fond Noir 41mm Homme/5_apnoir2.png",
                    "assets/img/audemars/Audemars Royal Oak Fond Noir 41mm Homme/2_ap2_716fb77f-2b54-442b-a46f-ca68283886c9.jpg",
                    "assets/img/audemars/Audemars Royal Oak Fond Noir 41mm Homme/1_ap5.jpg",
                    "assets/img/audemars/Audemars Royal Oak Fond Noir 41mm Homme/3_ap2_716fb77f-2b54-442b-a46f-ca68283886c9.jpg",
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/Audemars Offshore Diver 44 mm Noire/1_Lady_Dior_My_ABC_30.png',
                'alt' => 'Audemars Offshore Diver 44 mm Noire',
                'title' => 'Audemars Offshore Diver 44 mm Noire',
                'images' => [
                    "assets/img/audemars/Audemars Offshore Diver 44 mm Noire/1_Lady_Dior_My_ABC_30.png",
                    "assets/img/audemars/Audemars Offshore Diver 44 mm Noire/2_WhatsAppImage2023-04-09at04.29.44_4.jpg"
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/Audemars Piguet Royal Oak Double Balance Wheel Openworked 41mm/3_image_1280x_df84a040-3219-4ad2-b6a9-eabb07be21db.jpg',
                'alt' => 'Audemars Piguet Royal Oak Double Balance Wheel Openworked 41mm',
                'title' => 'Audemars Piguet Royal Oak Double Balance Wheel Openworked 41mm',
                'images' => [
                    "assets/img/audemars/Audemars Piguet Royal Oak Double Balance Wheel Openworked 41mm/3_image_1280x_df84a040-3219-4ad2-b6a9-eabb07be21db.jpg",
                    "assets/img/audemars/Audemars Piguet Royal Oak Double Balance Wheel Openworked 41mm/1_image_1280x_afe34699-f2bc-43f1-9f5c-fe6d280044ac.jpg",
                    "assets/img/audemars/Audemars Piguet Royal Oak Double Balance Wheel Openworked 41mm/2_Audemars-Piguet-Royal-Oak-Double-Balance-Wheel-Openworked-Black-Ceramic-2020-front-scaled.jpg",
                    "assets/img/audemars/Audemars Piguet Royal Oak Double Balance Wheel Openworked 41mm/5_image_1280x_273d7c90-386f-4ccf-b160-7754dfd76935.jpg",
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/Montre Homme Audemars Royal Oak Chronographe 41mm 26320ST.OO.1220ST/5_audemarsfdbleu.jpg',
                'alt' => 'Montre Homme Audemars Royal Oak Chronographe 41mm 26320ST.OO.1220ST',
                'title' => 'Montre Homme Audemars Royal Oak Chronographe 41mm 26320ST.OO.1220ST',
                'images' => [
                    "assets/img/audemars/Montre Homme Audemars Royal Oak Chronographe 41mm 26320ST.OO.1220ST/5_audemarsfdbleu.jpg",
                    "assets/img/audemars/Montre Homme Audemars Royal Oak Chronographe 41mm 26320ST.OO.1220ST/4_audemarsfdbleu4.jpg",
                    "assets/img/audemars/Montre Homme Audemars Royal Oak Chronographe 41mm 26320ST.OO.1220ST/3_audemarsfdbleu6.jpg",
                    "assets/img/audemars/Montre Homme Audemars Royal Oak Chronographe 41mm 26320ST.OO.1220ST/2_AudemarsPiguetRoyalOakChronograph41mm26320STOO1220ST02_a0cfe115-2a4b-4770-8c76-422e12f896e4.jpg",
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/audemars piguet royal oak chronograph panda/2_Audemars_Piguet_Royal_Oak_Chronograph_Panda_Watch_Vault_10_2048x_6d2cd53d-7562-4f7e-8b64-f7ea365079dd.jpg',
                'alt' => 'audemars piguet royal oak chronograph panda',
                'title' => 'audemars piguet royal oak chronograph panda',
                'images' => [
                    "assets/img/audemars/audemars piguet royal oak chronograph panda/2_Audemars_Piguet_Royal_Oak_Chronograph_Panda_Watch_Vault_10_2048x_6d2cd53d-7562-4f7e-8b64-f7ea365079dd.jpg",
                    "assets/img/audemars/audemars piguet royal oak chronograph panda/4_Audemars_Piguet_Royal_Oak_Chronograph_Panda_Watch_Vault_03_2048x_15be114c-167b-4d87-b766-b4c876e9a36c.jpg",
                    "assets/img/audemars/audemars piguet royal oak chronograph panda/1_Untitleddesign_96.png",
                    "assets/img/audemars/audemars piguet royal oak chronograph panda/5_2-6.jpg",
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/audemars/Audemars Diver Chronographe 42 mm Bleu/1_photo1664037830_1.jpg',
                'alt' => 'Audemars Diver Chronographe 42 mm Bleu',
                'title' => 'Audemars Diver Chronographe 42 mm Bleu',
                'images' => [
                    "assets/img/audemars/Audemars Diver Chronographe 42 mm Bleu/1_photo1664037830_1.jpg",
                    "assets/img/audemars/Audemars Diver Chronographe 42 mm Bleu/2_photo1664037852_2.jpg",
                    "assets/img/audemars/Audemars Diver Chronographe 42 mm Bleu/5_008_Royal-Oak-Offshore-Stainless-Steel-Gents-15710ST.jpg",
                    "assets/img/audemars/Audemars Diver Chronographe 42 mm Bleu/4_Untitleddesign_40.png",
                ],
                'slug' => 'audemars',
                'brand_slug' => 'audemars',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/hublot/Hublot Classic Fusion noir/2_s3b6530-4.jpg',
                'alt' => 'Hublot Classic Fusion noir',
                'title' => 'Hublot Classic Fusion noir',
                'images' => [
                    "assets/img/audemars/Hublot Classic Fusion noir/2_s3b6530-4.jpg",
                    "assets/img/audemars/Hublot Classic Fusion noir/3_0_s3b6514-1.jpg",
                    "assets/img/audemars/Hublot Classic Fusion noir/4_0_s3b6565-2.jpg",
                    "assets/img/audemars/Hublot Classic Fusion noir/1_BASE_LUXMMOMENT_2.jpg",
                ],
                'slug' => 'hublot',
                'brand_slug' => 'hublot',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/hublot/Hublot CLASSIC FUSION VERT/1_66f550b104dda0.jpg',
                'alt' => 'Hublot CLASSIC FUSION VERT',
                'title' => 'Hublot CLASSIC FUSION VERT',
                'images' => [
                    "assets/img/hublot/Hublot CLASSIC FUSION VERT/1_66f550b104dda0.jpg",
                    "assets/img/hublot/Hublot CLASSIC FUSION VERT/4_66f550b105d661.jpg",
                    "assets/img/hublot/Hublot CLASSIC FUSION VERT/3_mdyJj3uzuWbpWqNnDU3EjFi7TiAnAZras9HH1EuN_1.jpg",
                    "assets/img/hublot/Hublot CLASSIC FUSION VERT/2_66f550b105d661.jpg"
                ],
                'slug' => 'hublot',
                'brand_slug' => 'hublot',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/hublot/Hublot Big Bang/1_BASELUXREF_2.png',
                'alt' => 'Hublot Big Bang',
                'title' => 'Hublot Big Bang',
                'images' => [
                    "assets/img/hublot/Hublot Big Bang/1_BASELUXREF_2.png",
                    "assets/img/hublot/Hublot Big Bang/4_hublot-big-bang-44-mm_2.png",
                    "assets/img/hublot/Hublot Big Bang/3_hublot-big-bang-44-mm_1.png",
                    "assets/img/hublot/Hublot Big Bang/2_hublot-big-bang-44-mm.png"
                ],
                'slug' => 'hublot',
                'brand_slug' => 'hublot',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/hublot/Hublot Classic Fusion Racing/1_32390263-iefgrx2ipwi3mwd90aremz3a-ExtraLarge.jpg',
                'alt' => 'Hublot Classic Fusion Racing',
                'title' => 'Hublot Classic Fusion Racing',
                'images' => [
                    "assets/img/hublot/Hublot Classic Fusion Racing/1_32390263-iefgrx2ipwi3mwd90aremz3a-ExtraLarge.jpg",
                    "assets/img/hublot/Hublot Classic Fusion Racing/2_BASELUXREF_2.jpg",
                    "assets/img/hublot/Hublot Classic Fusion Racing/3_32390263-f9b0nwo8kuzhgcpmpwqurnhz-ExtraLarge.jpg"
                ],
                'slug' => 'hublot',
                'brand_slug' => 'hublot',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/hublot/Hublot Hublot Classic Fusion Titanium Blue 42mm/3_BASE_LUX_REF_7.png',
                'alt' => 'Hublot Hublot Classic Fusion Titanium Blue 42mm',
                'title' => 'Hublot Hublot Classic Fusion Titanium Blue 42mm',
                'images' => [
                    "assets/img/hublot/Hublot Hublot Classic Fusion Titanium Blue 42mm/3_BASE_LUX_REF_7.png",
                    "assets/img/hublot/Hublot Hublot Classic Fusion Titanium Blue 42mm/2_BASE_LUX_REF_8.png",
                    "assets/img/hublot/Hublot Hublot Classic Fusion Titanium Blue 42mm/1_BASELUXREF_5.png",
                    "assets/img/hublot/Hublot Hublot Classic Fusion Titanium Blue 42mm/4_BASE_LUX_REF_6.png"
                ],
                'slug' => 'hublot',
                'brand_slug' => 'hublot',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/hublot/Hublot CLASSIC FUSION JAUNE/2_D058DEF7-9F66-4DC9-A8C7-FE73B9DE5560.jpg',
                'alt' => 'Hublot CLASSIC FUSION JAUNE',
                'title' => 'Hublot CLASSIC FUSION JAUNE',
                'images' => [
                    "assets/img/hublot/Hublot CLASSIC FUSION JAUNE/2_D058DEF7-9F66-4DC9-A8C7-FE73B9DE5560.jpg",
                    "assets/img/hublot/Hublot CLASSIC FUSION JAUNE/1_465903007_17888466036128454_6048976367199474925_n.jpg",
                    "assets/img/hublot/Hublot CLASSIC FUSION JAUNE/3_EA2FA525-AC06-4418-999E-1792F93637B0.jpg"
                ],
                'slug' => 'hublot',
                'brand_slug' => 'hublot',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/hublot/Hublot Classic Fusion Titanium Green 42mm/5_BASE_LUXMMOMENT_16.jpg',
                'alt' => 'Hublot Classic Fusion Titanium Green 42mm',
                'title' => 'Hublot Classic Fusion Titanium Green 42mm',
                'images' => [
                    "assets/img/hublot/Hublot Classic Fusion Titanium Green 42mm/5_BASE_LUXMMOMENT_16.jpg",
                    "assets/img/hublot/Hublot Classic Fusion Titanium Green 42mm/2_17170946_5.jpg",
                    "assets/img/hublot/Hublot Classic Fusion Titanium Green 42mm/4_17170946_7.jpg",
                    "assets/img/hublot/Hublot Classic Fusion Titanium Green 42mm/1_17170946_8.jpg",
                ],
                'slug' => 'hublot',
                'brand_slug' => 'hublot',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/hublot/Hublot Classic Fusion King Gold Blue/3_Classic-Fusion-King-Gold-Blue-42-mm-ad-shot.jpg',
                'alt' => 'Hublot Classic Fusion King Gold Blue',
                'title' => 'Hublot Classic Fusion King Gold Blue',
                'images' => [
                    "assets/img/hublot/Hublot Classic Fusion King Gold Blue/3_Classic-Fusion-King-Gold-Blue-42-mm-ad-shot.jpg",
                    "assets/img/hublot/Hublot Classic Fusion King Gold Blue/1_LadyDiorMyABC_4.png",
                    "assets/img/hublot/Hublot Classic Fusion King Gold Blue/4_Classic-Fusion-King-Gold-Blue-42-mm-lifestyle-shot.jpg",
                    "assets/img/hublot/Hublot Classic Fusion King Gold Blue/5_Classic-Fusion-King-Gold-Blue-42-mm-close-up-shot.jpg",
                ],
                'slug' => 'hublot',
                'brand_slug' => 'hublot',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/richardmille/Richard Mille RM 011 Jaune/4_15523190-13z7kdxnycki7tc3wuy1x93j-Zoom.jpg',
                'alt' => 'Richard Mille RM 011 Jaune',
                'title' => 'Richard Mille RM 011 Jaune',
                'images' => [
                    "assets/img/richardmille/Richard Mille RM 011 Jaune/4_15523190-13z7kdxnycki7tc3wuy1x93j-Zoom.jpg",
                    "assets/img/richardmille/Richard Mille RM 011 Jaune/5_15523190-ycysta8msunsqf6n4xpgnp14-Zoom.jpg",
                    "assets/img/richardmille/Richard Mille RM 011 Jaune/3_15523190-w5ohjseyjm7jtco9v2essx6l-Zoom.jpg",
                    "assets/img/richardmille/Richard Mille RM 011 Jaune/1_123603946_425909642138497_5770804937536754074_n.jpg",
                ],
                'slug' => 'richardmille',
                'brand_slug' => 'richardmille',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/richardmille/Richard mille RM65-01 noir/1_33317392-6cyp262i3r38iaxaz4xritzu-Zoom.jpg',
                'alt' => 'Richard mille RM65-01 noir',
                'title' => 'Richard mille RM65-01 noir',
                'images' => [
                    "assets/img/richardmille/Richard mille RM65-01 noir/1_33317392-6cyp262i3r38iaxaz4xritzu-Zoom.jpg",
                    "assets/img/richardmille/Richard mille RM65-01 noir/2_33317392-jbrvw3ravk779ct6j5shpxmr-Zoom.jpg",
                    "assets/img/richardmille/Richard mille RM65-01 noir/3_Untitleddesign_92.png",
                    "assets/img/richardmille/Richard mille RM65-01 noir/4_33317392-wb2xbpptx5lp902laa6gpuus-Zoom.jpg"
                ],
                'slug' => 'richardmille',
                'brand_slug' => 'richardmille',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/richardmille/Richard mille RM65-01 Gold/2_28949872-56epikwacv3yi25cuceo7fiy-Zoom.jpg',
                'alt' => 'Richard mille RM65-01 Gold',
                'title' => 'Richard mille RM65-01 Gold',
                'images' => [
                    "assets/img/richardmille/Richard mille RM65-01 Gold/2_28949872-56epikwacv3yi25cuceo7fiy-Zoom.jpg",
                    "assets/img/richardmille/Richard mille RM65-01 Gold/4_28949872-6r1z8i9tbgtpqzt9iqsughhs-Zoom.jpg",
                    "assets/img/richardmille/Richard mille RM65-01 Gold/1_28949872-56epikwacv3yi25cuceo7fiy-Zoom.jpg",
                    "assets/img/richardmille/Richard mille RM65-01 Gold/3_28949872-56epikwacv3yi25cuceo7fiy-Zoom.jpg"
                ],
                'slug' => 'richardmille',
                'brand_slug' => 'richardmille',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/richardmille/Richard mille RM 65-01 gris/2_2024-05-0713.53.42.jpg',
                'alt' => 'Richard mille RM 65-01 gris',
                'title' => 'Richard mille RM 65-01 gris',
                'images' => [
                    "assets/img/richardmille/Richard mille RM 65-01 gris/2_2024-05-0713.53.42.jpg",
                    "assets/img/richardmille/Richard mille RM 65-01 gris/3_2024-05-0713.53.36.jpg",
                    "assets/img/richardmille/Richard mille RM 65-01 gris/4_364681720_18381205465004303_6790657388004308783_n.jpg",
                    "assets/img/richardmille/Richard mille RM 65-01 gris/1_2024-05-0713.53.45.jpg",
                ],
                'slug' => 'richardmille',
                'brand_slug' => 'richardmille',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/cartier/Santos bleu/3_w1242_tpadding12_3_2f740fcd-04fc-4bc0-9fd3-dccf51917741.jpg',
                'alt' => 'Santos bleu',
                'title' => 'Santos bleu',
                'images' => [
                    "assets/img/cartier/Santos bleu/3_w1242_tpadding12_3_2f740fcd-04fc-4bc0-9fd3-dccf51917741.jpg",
                    "assets/img/cartier/Santos bleu/4_w1242_tpadding12_1_2d8e1819-89c4-4909-8015-209d9e94c30a.jpg",
                    "assets/img/cartier/Santos bleu/2_w1242_tpadding12_2_073dfc3b-495f-4fca-9791-824846784da7.jpg",
                    "assets/img/cartier/Santos bleu/1_w1242_tpadding12_4_1bfe500a-ea92-40c8-9bea-ae0a6b831348.jpg",
                ],
                'slug' => 'cartier',
                'brand_slug' => 'cartier',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/cartier/Cartier Santos bleu/4_BASE_LUX_REF_12.jpg',
                'alt' => 'Cartier Santos bleu',
                'title' => 'Cartier Santos bleu',
                'images' => [
                    "assets/img/cartier/Cartier Santos bleu/4_BASE_LUX_REF_12.jpg",
                    "assets/img/cartier/Cartier Santos bleu/5_9c6045d5101ae5edee8dbb1bb69c170e-4CKBQMRu8QmhJUi1pjey_1.jpg",
                    "assets/img/cartier/Cartier Santos bleu/2_cartier-santos_3.png",
                    "assets/img/cartier/Cartier Santos bleu/3_9882808a0c935e22efdd624ebe3a5105-T7W4ie6EiDyc4aBqEe5V_1.jpg",
                ],
                'slug' => 'cartier',
                'brand_slug' => 'cartier',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/cartier/Cartier Skeleton Argenté/1_32658058-3t6w4us8nrtxqb5b6w8dzapg-Zoom.jpg',
                'alt' => 'Cartier Skeleton Argenté',
                'title' => 'Cartier Skeleton Argenté',
                'images' => [
                    "assets/img/cartier/Cartier Skeleton Argenté/1_32658058-3t6w4us8nrtxqb5b6w8dzapg-Zoom.jpg",
                    "assets/img/cartier/Cartier Skeleton Argenté/2_32658058-lpm2x82cklhwhwbt5a8dfm8s-Zoom.jpg",
                    "assets/img/cartier/Cartier Skeleton Argenté/3_32658058-0d606j7kjx82wrx3tk9s5h1j-Zoom.jpg"
                ],
                'slug' => 'cartier',
                'brand_slug' => 'cartier',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/cartier/Cartier Tank Louiss Noir/1_w1242_tpadding12-23.jpg',
                'alt' => 'Cartier Tank Louiss Noir',
                'title' => 'Cartier Tank Louiss Noir',
                'images' => [
                    "assets/img/cartier/Cartier Tank Louiss Noir/1_w1242_tpadding12-23.jpg",
                    "assets/img/cartier/Cartier Tank Louiss Noir/4_w1242_tpadding12-25.jpg",
                    "assets/img/cartier/Cartier Tank Louiss Noir/3_LadyDiorMyABC_4_d8924182-7721-4e27-b751-74f955a10931.png",
                    "assets/img/cartier/Cartier Tank Louiss Noir/2_w1242_tpadding12-22.jpg"
                ],
                'slug' => 'cartier',
                'brand_slug' => 'cartier',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/cartier/Cartier Skeleton Doré et Argenté/3_33790327-2bvg2q9z1zbsoivf6m0n2mtd-Zoom.jpg',
                'alt' => 'Cartier Skeleton Doré et Argenté',
                'title' => 'Cartier Skeleton Doré et Argenté',
                'images' => [
                    "assets/img/cartier/Cartier Skeleton Doré et Argenté/3_33790327-2bvg2q9z1zbsoivf6m0n2mtd-Zoom.jpg",
                    "assets/img/cartier/Cartier Skeleton Doré et Argenté/1_33790327-channsj1ygi0la2in3kepnv1-Zoom.jpg",
                    "assets/img/cartier/Cartier Skeleton Doré et Argenté/4_33790327-db5us86yi23pgkx3r6gxyqmx-Zoom.jpg",
                    "assets/img/cartier/Cartier Skeleton Doré et Argenté/5_33790327-wgjuxp70bpip5e8u24n0pp7w-Zoom.jpg",
                ],
                'slug' => 'cartier',
                'brand_slug' => 'cartier',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/cartier/Cartier Drive/4_cartier-drive_2.png',
                'alt' => 'Cartier Drive',
                'title' => 'Cartier Drive',
                'images' => [
                    "assets/img/cartier/Cartier Drive/4_cartier-drive_2.png",
                    "assets/img/cartier/Cartier Drive/2_BASELUXREF_21.jpg",
                    "assets/img/cartier/Cartier Drive/3_cartier-drive_4.png",
                    "assets/img/cartier/Cartier Drive/1_5750db5f-5431-4965-b7e9-e7835ec3ac73.jpg",
                ],
                'slug' => 'cartier',
                'brand_slug' => 'cartier',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/cartier/Cartier Santos WSSA0037 Pour Homme/4_Lady_Dior_My_ABC_7_7cff0dd5-27b5-4999-adc4-55db1393cca7.png',
                'alt' => 'Cartier Santos WSSA0037 Pour Homme',
                'title' => 'Cartier Santos WSSA0037 Pour Homme',
                'images' => [
                    "assets/img/cartier/Cartier Santos WSSA0037 Pour Homme/4_Lady_Dior_My_ABC_7_7cff0dd5-27b5-4999-adc4-55db1393cca7.png",
                    "assets/img/cartier/Cartier Santos WSSA0037 Pour Homme/2_w1242_tpadding12_4_e830a1b5-8712-43c8-b5cd-3921f67aa947.jpg",
                    "assets/img/cartier/Cartier Santos WSSA0037 Pour Homme/5_w1242_tpadding12_1_76408328-30e5-4604-ba63-813762489002.jpg",
                    "assets/img/cartier/Cartier Santos WSSA0037 Pour Homme/1_w1242_tpadding12_3_c3a7b1e8-43cc-42d6-9924-571f42c4a23e.jpg",
                ],
                'slug' => 'cartier',
                'brand_slug' => 'cartier',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/cartier/cartier Santos blanc/1_w1242_tpadding12_3_3df03222-50e6-47a9-9927-7aa0ff666d95.jpg',
                'alt' => 'cartier Santos blanc',
                'title' => 'cartier Santos blanc',
                'images' => [
                    "assets/img/cartier/cartier Santos blanc/1_w1242_tpadding12_3_3df03222-50e6-47a9-9927-7aa0ff666d95.jpg",
                    "assets/img/cartier/cartier Santos blanc/2_w1242_tpadding12_4_761fc010-3455-40e9-8603-97859986391b.jpg",
                    "assets/img/cartier/cartier Santos blanc/3_Designsanstitre_51aa8ade-92ab-4416-85ec-ce6d1c241a6a.png",
                    "assets/img/cartier/cartier Santos blanc/4_w1242_tpadding12_1_1ecfb002-74d6-4bae-87cb-c9a8a985c000.jpg",
                ],
                'slug' => 'cartier',
                'brand_slug' => 'cartier',
                'price' => '850',
                'price_packaging' => '999',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/tissot/TISSOT PRX POWERMATIC 80Noir/1_205.png',
                'alt' => 'TISSOT PRX POWERMATIC 80Noir',
                'title' => 'TISSOT PRX POWERMATIC 80Noir',
                'images' => [
                    "assets/img/tissot/TISSOT PRX POWERMATIC 80Noir/1_205.png"
                ],
                'slug' => 'tissot',
                'brand_slug' => 'tissot',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/tissot/TISSOT PRX POWERMATIC 80 Bleu/1_T137.407.11.041.00_AMB_S_1.webp',
                'alt' => 'TISSOT PRX POWERMATIC 80 Bleu',
                'title' => 'TISSOT PRX POWERMATIC 80 Bleu',
                'images' => [
                    "assets/img/tissot/TISSOT PRX POWERMATIC 80 Bleu/1_T137.407.11.041.00_AMB_S_1.webp",
                    "assets/img/tissot/TISSOT PRX POWERMATIC 80 Bleu/2_204.png"
                ],
                'slug' => 'tissot',
                'brand_slug' => 'tissot',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/tissot/TISSOT PRX POWERMATIC 80 Vert/1_207.png',
                'alt' => 'TISSOT PRX POWERMATIC 80 Vert',
                'title' => 'TISSOT PRX POWERMATIC 80 Vert',
                'images' => [
                    "assets/img/tissot/TISSOT PRX POWERMATIC 80 Vert/1_207.png"
                ],
                'slug' => 'tissot',
                'brand_slug' => 'tissot',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/tissot/TISSOT PRX POWERMATIC 80 Blanche/1_206.png',
                'alt' => 'TISSOT PRX POWERMATIC 80 Blanche',
                'title' => 'TISSOT PRX POWERMATIC 80 Blanche',
                'images' => [
                    "assets/img/tissot/TISSOT PRX POWERMATIC 80 Blanche/1_206.png",
                ],
                'slug' => 'tissot',
                'brand_slug' => 'tissot',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/patekphilippe/Patek Philippe Nautilus/4_36981801-nafjj287x70xecxy7wooxrd8-ExtraLarge.jpg',
                'alt' => 'Patek Philippe Nautilus',
                'title' => 'Patek Philippe Nautilus',
                'images' => [
                    "assets/img/patekphilippe/Patek Philippe Nautilus/4_36981801-nafjj287x70xecxy7wooxrd8-ExtraLarge.jpg",
                    "assets/img/patekphilippe/Patek Philippe Nautilus/5_BASELUXREF_22.png",
                    "assets/img/patekphilippe/Patek Philippe Nautilus/2_36981801-1em4otbsnmckgpv9aqzjf6wy-ExtraLarge.jpg",
                    "assets/img/patekphilippe/Patek Philippe Nautilus/1_36981801-la0p6uhx4v3vs9xiwrjhci26-ExtraLarge.jpg",
                ],
                'slug' => 'patekphilippe',
                'brand_slug' => 'patekphilippe',
                'price' => '850',
                'price_packaging' => '1000',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/patekphilippe/Patek Philippe Aquanaut bleu/1_32833548-hdk663juo1ipvv6qw9zc1t57-ExtraLarge.jpg',
                'alt' => 'Patek Philippe Aquanaut bleu',
                'title' => 'Patek Philippe Aquanaut bleu',
                'images' => [
                    "assets/img/patekphilippe/Patek Philippe Aquanaut bleu/1_32833548-hdk663juo1ipvv6qw9zc1t57-ExtraLarge.jpg",
                    "assets/img/patekphilippe/Patek Philippe Aquanaut bleu/3_20417041-6421klt0oct9kesgggf91w2g-ExtraLarge.jpg",
                    "assets/img/patekphilippe/Patek Philippe Aquanaut bleu/5_ptk_1800x1800_f2be5509-1997-4d94-b978-d2705cf788f3.jpg",
                    "assets/img/patekphilippe/Patek Philippe Aquanaut bleu/2_20417041-3fsbbi3dkhaotnu851vpad7z-ExtraLarge.jpg",
                ],
                'slug' => 'patekphilippe',
                'brand_slug' => 'patekphilippe',
                'price' => '850',
                'price_packaging' => '1000',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/patekphilippe/Patek Philippe 5968A - AQUANAUT/1_BASE_LUX_REF_32.png',
                'alt' => 'Patek Philippe 5968A - AQUANAUT',
                'title' => 'Patek Philippe 5968A - AQUANAUT',
                'images' => [
                    "assets/img/patekphilippe/Patek Philippe 5968A - AQUANAUT/1_BASE_LUX_REF_32.png",
                    "assets/img/patekphilippe/Patek Philippe 5968A - AQUANAUT/2_E8BE86E7-6F21-4287-A289-E901782BDD58.webp"
                ],
                'slug' => 'patekphilippe',
                'brand_slug' => 'patekphilippe',
                'price' => '850',
                'price_packaging' => '1000',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/patekphilippe/Patek Philippe 5968G - AQUANAUT/2_Screen_Shot_2020-07-20_at_4.59.06_PM.png',
                'alt' => 'Patek Philippe 5968G - AQUANAUT',
                'title' => 'Patek Philippe 5968G - AQUANAUT',
                'images' => [
                    "assets/img/patekphilippe/Patek Philippe 5968G - AQUANAUT/2_Screen_Shot_2020-07-20_at_4.59.06_PM.png",
                    "assets/img/patekphilippe/Patek Philippe 5968G - AQUANAUT/3_5968G_010_12_2x_0b3e95fb-4f7f-4d8d-9975-98036eb0c78a.jpg",
                    "assets/img/patekphilippe/Patek Philippe 5968G - AQUANAUT/1_150.png",
                    "assets/img/patekphilippe/Patek Philippe 5968G - AQUANAUT/4_5968G_010_16_2x_323d8fdc-5424-4570-b2a7-9269da7f03e9.jpg",
                ],
                'slug' => 'patekphilippe',
                'brand_slug' => 'patekphilippe',
                'price' => '850',
                'price_packaging' => '1000',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/patekphilippe/Patek Philippe Nautilus Vert Dial/2_23478503-8ctt9h19stumdrghzenbti6f-ExtraLarge.webp',
                'alt' => 'Patek Philippe Nautilus Vert Dial',
                'title' => 'Patek Philippe Nautilus Vert Dial',
                'images' => [
                    "assets/img/patekphilippe/Patek Philippe Nautilus Vert Dial/2_23478503-8ctt9h19stumdrghzenbti6f-ExtraLarge.webp",
                    "assets/img/patekphilippe/Patek Philippe Nautilus Vert Dial/4_Untitleddesign_26.png",
                    "assets/img/patekphilippe/Patek Philippe Nautilus Vert Dial/1_patek-philippe-nautilus-5711-1a-014-stainless-steel-green-dial-patek-philippe-40740412326132_1280x_bfa96ad3-08f9-4522-b13b-0f8e2e09ba42.webp",
                    "assets/img/patekphilippe/Patek Philippe Nautilus Vert Dial/3_patek-5711-014-06.jpg",
                ],
                'slug' => 'patekphilippe',
                'brand_slug' => 'patekphilippe',
                'price' => '850',
                'price_packaging' => '1000',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/patekphilippe/Patek Philippe/4_patek11_17274e7a-e57d-4170-80b2-facd84d1b94e.jpg',
                'alt' => 'Patek Philippe',
                'title' => 'Patek Philippe',
                'images' => [
                    "assets/img/patekphilippe/Patek Philippe/4_patek11_17274e7a-e57d-4170-80b2-facd84d1b94e.jpg",
                    "assets/img/patekphilippe/Patek Philippe/5_BASE_LUX_REF_20.png",
                    "assets/img/patekphilippe/Patek Philippe/3_patek16_c58ed6f0-78a1-4e4d-9a2a-33c8583f1911.jpg",
                    "assets/img/patekphilippe/Patek Philippe/2_patek12_7bbb4770-9fc2-4404-b990-1976d5424b83.jpg",
                ],
                'slug' => 'patekphilippe',
                'brand_slug' => 'patekphilippe',
                'price' => '850',
                'price_packaging' => '1000',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/patekphilippe/Patek Philippe Aquanaut marron/3_27621978-8glaj1qci3ujw9dbl0fpz6b4-ExtraLarge.jpg',
                'alt' => 'Patek Philippe Aquanaut marron',
                'title' => 'Patek Philippe Aquanaut marron',
                'images' => [
                    "assets/img/patekphilippe/Patek Philippe Aquanaut marron/3_27621978-8glaj1qci3ujw9dbl0fpz6b4-ExtraLarge.jpg",
                    "assets/img/patekphilippe/Patek Philippe Aquanaut marron/2_27621978-s97suhk2gkafvtk4rticogo2-ExtraLarge.jpg",
                    "assets/img/patekphilippe/Patek Philippe Aquanaut marron/5_BASELUXREF_1.jpg",
                    "assets/img/patekphilippe/Patek Philippe Aquanaut marron/6_BASELUXREF_1.jpg",
                ],
                'slug' => 'patekphilippe',
                'brand_slug' => 'patekphilippe',
                'price' => '850',
                'price_packaging' => '1000',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/patekphilippe/Patek Philippe Nautilus blanc/5_BASELUXREF_30.png',
                'alt' => 'Patek Philippe Nautilus blanc',
                'title' => 'Patek Philippe Nautilus blanc',
                'images' => [
                    "assets/img/patekphilippe/Patek Philippe Nautilus blanc/5_BASELUXREF_30.png",
                    "assets/img/patekphilippe/Patek Philippe Nautilus blanc/1_kzbhnv01p22272-600x600_1.webp",
                    "assets/img/patekphilippe/Patek Philippe Nautilus blanc/2_girwwktdeox277-600x600.webp",
                    "assets/img/patekphilippe/Patek Philippe Nautilus blanc/3_czmy4unr22d273-600x600.webp",
                ],
                'slug' => 'patekphilippe',
                'brand_slug' => 'patekphilippe',
                'price' => '850',
                'price_packaging' => '1000',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/patekphilippe/Patek Philippe Nautilus blanc/5_BASELUXREF_30.png',
                'alt' => 'Patek Philippe Aquanaut noir',
                'title' => 'Patek Philippe Aquanaut noir',
                'images' => [
                    "assets/img/patekphilippe/Patek Philippe Aquanaut noir/1_33603791-wb9f226xog89k5vh5xunsvex-ExtraLarge.jpg",
                    "assets/img/patekphilippe/Patek Philippe Aquanaut noir/2_33603791-mysmfex5r8murmmjfp78jgof-ExtraLarge.jpg",
                    "assets/img/patekphilippe/Patek Philippe Aquanaut noir/3_23549924-ipffv7qdao61vpzem2v8djg2-ExtraLarge.jpg",
                    "assets/img/patekphilippe/Patek Philippe Aquanaut noir/4_BASE_LUX_REF_ebab2695-9dc6-4966-8f9a-fee8df9235ef.jpg"
                ],
                'slug' => 'patekphilippe',
                'brand_slug' => 'patekphilippe',
                'price' => '850',
                'price_packaging' => '1000',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/patekphilippe/Patek Philippe Nautilus blanc/5_BASELUXREF_30.png',
                'alt' => 'Montre Datejust 41 Blanc Jubilé Pour Homme',
                'title' => 'Montre Datejust 41 Blanc Jubilé Pour Homme',
                'images' => [
                    "assets/img/rolex/Montre Datejust 41 Blanc Jubilé Pour Homme/ROLEX126334_891a437c-c86a-45d5-9a36-eafcd95d89fc.jpg",
                    "assets/img/rolex/Montre Datejust 41 Blanc Jubilé Pour Homme/ROLEX126334_eaceaaa2-d74c-4536-b7ff-bee5b37f2d23.jpg",
                    "assets/img/rolex/Montre Datejust 41 Blanc Jubilé Pour Homme/ROLEX126334_0bb1410c-3010-4cdc-a547-5f3cdd9da7bf.jpg",
                    "assets/img/rolex/Montre Datejust 41 Blanc Jubilé Pour Homme/Untitleddesign_64.png",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/GMT-MASTER II Pepsi Montre Pour Homme/WhatsAppImage2020-10-13at21.45.35.jpg',
                'alt' => 'GMT-MASTER II Pepsi Montre Pour Homme',
                'title' => 'GMT-MASTER II Pepsi Montre Pour Homme',
                'images' => [
                    "assets/img/rolex/GMT-MASTER II Pepsi Montre Pour Homme/WhatsAppImage2020-10-13at21.45.35.jpg",
                    "assets/img/rolex/GMT-MASTER II Pepsi Montre Pour Homme/Rolex-GMT-Master-II-GMTMasterI2018-Pepsi.jpg",
                    "assets/img/rolex/GMT-MASTER II Pepsi Montre Pour Homme/Untitleddesign_29.png",
                    "assets/img/rolex/GMT-MASTER II Pepsi Montre Pour Homme/5_6b24ffed-73e7-43fb-9fba-21e95cc70335.png",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/GMT-Master II Jubilée Pour Homme/Rolex-GMT-Master-II-Steel-and-Yellow-Gold-Jubilee-Bracelet-2023-two-tone-126713GRNR-hands-on-review-8.jpg',
                'alt' => 'GMT-Master II Jubilée Pour Homme',
                'title' => 'GMT-Master II Jubilée Pour Homme',
                'images' => [
                    "assets/img/rolex/GMT-Master II Jubilée Pour Homme/Rolex-GMT-Master-II-Steel-and-Yellow-Gold-Jubilee-Bracelet-2023-two-tone-126713GRNR-hands-on-review-8.jpg",
                    "assets/img/rolex/GMT-Master II Jubilée Pour Homme/Rolex-GMT-MasterII-126713GRNR-Colognewatch-11-7348_f6e39b77-c743-44c8-9887-9bea41a29754.webp",
                    "assets/img/rolex/GMT-Master II Jubilée Pour Homme/effe.png",
                    "assets/img/rolex/GMT-Master II Jubilée Pour Homme/Cover2-TT-scaled_5596ed4d-c013-4d77-938f-fd90971a9821.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Rolex Day-Date 40 blanc/OrangeSimpleIllustratiionOnlineShopLogo_6_fb010ff7-ecb7-4f52-be25-689d38eaa320.jpg',
                'alt' => 'Rolex Day-Date 40 blanc',
                'title' => 'Rolex Day-Date 40 blanc',
                'images' => [
                    "assets/img/rolex/Rolex Day-Date 40 blanc/OrangeSimpleIllustratiionOnlineShopLogo_6_fb010ff7-ecb7-4f52-be25-689d38eaa320.jpg",
                    "assets/img/rolex/Rolex Day-Date 40 blanc/31230811-4qzebcbz4nrfcy0ecakmxfq5-ExtraLarge.jpg",
                    "assets/img/rolex/Rolex Day-Date 40 blanc/31231738-k33auxwa53y3rtqp3h8z3mow-ExtraLarge.jpg",
                    "assets/img/rolex/Rolex Day-Date 40 blanc/31230811-e60hlm1pnwhfv6elf91un5xp-ExtraLarge.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/bruce wayne/s-l1600_6.webp',
                'alt' => 'bruce wayne',
                'title' => 'bruce wayne',
                'images' => [
                    "assets/img/rolex/bruce wayne/s-l1600_6.webp",
                    "assets/img/rolex/bruce wayne/s-l1600_8.webp",
                    "assets/img/rolex/bruce wayne/s-l1600_2.webp",
                    "assets/img/rolex/bruce wayne/s-l1600_1.webp",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Montre Datejust 41 Noir Jubilé Pour Homme/9_ef81332d-44e9-43b6-ba9d-19c4b13261a6.png',
                'alt' => 'Montre Datejust 41 Noir Jubilé Pour Homme',
                'title' => 'Montre Datejust 41 Noir Jubilé Pour Homme',
                'images' => [
                    "assets/img/rolex/Montre Datejust 41 Noir Jubilé Pour Homme/9_ef81332d-44e9-43b6-ba9d-19c4b13261a6.png",
                    "assets/img/rolex/Montre Datejust 41 Noir Jubilé Pour Homme/ROLEXdatejust126334-0018_cb652f31-a450-47e2-9f0a-056c69a50d01.jpg",
                    "assets/img/rolex/Montre Datejust 41 Noir Jubilé Pour Homme/ROLEX126334_62eb6fc4-daa5-4f5c-82ad-59aa9e1ef44b.jpg",
                    "assets/img/rolex/Montre Datejust 41 Noir Jubilé Pour Homme/ROLEXdatejust126334-0018_a3590b69-a8e3-4b34-ba86-7605a040bc0b.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/ROLEX PLATINUM DAY-DATE 41MM/5_rolex-day-date-228206-iceblueromind-multiple-1_1.jpg',
                'alt' => 'ROLEX PLATINUM DAY-DATE 41MM',
                'title' => 'ROLEX PLATINUM DAY-DATE 41MM',
                'images' => [
                    "assets/img/rolex/ROLEX PLATINUM DAY-DATE 41MM/5_rolex-day-date-228206-iceblueromind-multiple-1_1.jpg",
                    "assets/img/rolex/ROLEX PLATINUM DAY-DATE 41MM/2_rolex-day-date-228206-iceblueromind-multiple-6_1.jpg",
                    "assets/img/rolex/ROLEX PLATINUM DAY-DATE 41MM/3_181705-2_1680x_3fcadb7b-2aea-4c16-9785-1626a3cd6547.jpg",
                    "assets/img/rolex/ROLEX PLATINUM DAY-DATE 41MM/4_rolex-day-date-228206-iceblueromind-multiple-4_1.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Yacht-Master II 116688 44mm Pour Homme/4_MontreRolexYacht-MasterII11668844mmPourHomme_870f0cfe-3591-4ae8-8cf9-f1bfda51ec10.jpg',
                'alt' => 'Yacht-Master II 116688 44mm Pour Homme',
                'title' => 'Yacht-Master II 116688 44mm Pour Homme',
                'images' => [
                    "assets/img/rolex/Yacht-Master II 116688 44mm Pour Homme/4_MontreRolexYacht-MasterII11668844mmPourHomme_870f0cfe-3591-4ae8-8cf9-f1bfda51ec10.jpg",
                    "assets/img/rolex/Yacht-Master II 116688 44mm Pour Homme/1_yachtmasterdoree_821d08e0-8045-4e03-acce-6d3d3977cc33.jpg",
                    "assets/img/rolex/Yacht-Master II 116688 44mm Pour Homme/3_MontreRolexYacht-MasterII11668844mmPourHomme_9e6e5630-9d46-4cd9-8121-1087cc99e8e6.jpg",
                    "assets/img/rolex/Yacht-Master II 116688 44mm Pour Homme/2_r446.jpg"
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Submariner Vert _Hulk_ 116610LV Pour Homme/WhatsApp_Image_2020-02-26_at_21.36.39_1_1.jpg',
                'alt' => 'Submariner Vert _Hulk_ 116610LV Pour Homme',
                'title' => 'Submariner Vert _Hulk_ 116610LV Pour Homme',
                'images' => [
                    "assets/img/rolex/Submariner Vert _Hulk_ 116610LV Pour Homme/WhatsApp_Image_2020-02-26_at_21.36.39_1_1.jpg",
                    "assets/img/rolex/Submariner Vert _Hulk_ 116610LV Pour Homme/84243620_275627480077467_8839299816938445999_n_2.jpg",
                    "assets/img/rolex/Submariner Vert _Hulk_ 116610LV Pour Homme/WhatsApp_Image_2020-02-26_at_21.36.40_1.jpg",
                    "assets/img/rolex/Submariner Vert _Hulk_ 116610LV Pour Homme/WhatsAppImage2020-10-13at21.44.20.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Datejust 36 mm Bleu 126234 Modèle 2021/datejustnew7_417de841-743f-4f24-a517-508857cd1a3a.jpg',
                'alt' => 'Datejust 36 mm Bleu 126234 Modèle 2021',
                'title' => 'Datejust 36 mm Bleu 126234 Modèle 2021',
                'images' => [
                    "assets/img/rolex/Datejust 36 mm Bleu 126234 Modèle 2021/datejustnew7_417de841-743f-4f24-a517-508857cd1a3a.jpg",
                    "assets/img/rolex/Datejust 36 mm Bleu 126234 Modèle 2021/datejustnew8_fd87adad-ee58-4768-8a42-ee5c94f4c87c.jpg",
                    "assets/img/rolex/Datejust 36 mm Bleu 126234 Modèle 2021/r4.jpg",
                    "assets/img/rolex/Datejust 36 mm Bleu 126234 Modèle 2021/datejustnew2_8c420bbc-c9a6-4ff6-a50d-eeda072fd541.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Yacht-Master II 116680 44mm Pour Homme/5_MontreRolexYacht-MasterII11668044mmPourHomme_096cc691-1ad5-4a71-95bf-72e304fb8bb4.jpg',
                'alt' => 'Yacht-Master II 116680 44mm Pour Homme',
                'title' => 'Yacht-Master II 116680 44mm Pour Homme',
                'images' => [
                    "assets/img/rolex/Yacht-Master II 116680 44mm Pour Homme/5_MontreRolexYacht-MasterII11668044mmPourHomme_096cc691-1ad5-4a71-95bf-72e304fb8bb4.jpg",
                    "assets/img/rolex/Yacht-Master II 116680 44mm Pour Homme/1_r44.png",
                    "assets/img/rolex/Yacht-Master II 116680 44mm Pour Homme/4_MontreRolexYacht-MasterII11668044mmPourHomme_fd2116ee-b477-4137-b6a4-1192395fc812.jpg",
                    "assets/img/rolex/Yacht-Master II 116680 44mm Pour Homme/3_MontreRolexYacht-MasterII11668044mmPourHomme_0eeeab37-aaaa-4809-a5e6-0b1b1fdb2c41.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Daytona Cosmographe Fond Blanc Montre Pour Homme/12.png',
                'alt' => 'Daytona Cosmographe Fond Blanc Montre Pour Homme',
                'title' => 'Daytona Cosmographe Fond Blanc Montre Pour Homme',
                'images' => [
                    "assets/img/rolex/Daytona Cosmographe Fond Blanc Montre Pour Homme/12.png",
                    "assets/img/rolex/Daytona Cosmographe Fond Blanc Montre Pour Homme/dayonafondblanc116500LN_9c91a3a6-2a59-40d5-93a6-341a17acff19.jpg",
                    "assets/img/rolex/Daytona Cosmographe Fond Blanc Montre Pour Homme/dayonafondblanc116500LN.jpg",
                    "assets/img/rolex/Daytona Cosmographe Fond Blanc Montre Pour Homme/dayonafondblanc116500LN_82f18efc-d0a6-4b9c-aa1c-b3d29907a3b6.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Rolex gold and black/1_DSC01424_41a16dde-7e32-4e03-b8f0-8d8760d15d54.jpg',
                'alt' => 'Rolex gold and black',
                'title' => 'Rolex gold and black',
                'images' => [
                    "assets/img/rolex/Rolex gold and black/1_DSC01424_41a16dde-7e32-4e03-b8f0-8d8760d15d54.jpg",
                    "assets/img/rolex/Rolex gold and black/3_s-l500_1_18b0aa48-ee29-4904-a7b6-ebf647f151bf.png",
                    "assets/img/rolex/Rolex gold and black/5_Sub-FG-126618LN-New-1-1-600x600_9eefb3a5-e5da-48b1-a185-8fce11cc7c70.webp",
                    "assets/img/rolex/Rolex gold and black/4_m126618ln-0002_b06e0034-0e6a-445b-a267-e28f06dc7b26.webp",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris2.png',
                'alt' => 'Daytona Cosmographe gris 116518LN',
                'title' => 'Daytona Cosmographe gris 116518LN',
                'images' => [
                    "assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris2.png",
                    "assets/img/rolex/Daytona Cosmographe gris 116518LN/r13.jpg",
                    "assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris5.png",
                    "assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris1.png",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/datejust fond vert 41mm/3_126300-green-jub-126300-0020-3-510x680.webp',
                'alt' => 'datejust fond vert 41mm',
                'title' => 'datejust fond vert 41mm',
                'images' => [
                    "assets/img/rolex/datejust fond vert 41mm/3_126300-green-jub-126300-0020-3-510x680.webp",
                    "assets/img/rolex/datejust fond vert 41mm/4_126300-green-jub-126300-0020-2-510x680.webp",
                    "assets/img/rolex/datejust fond vert 41mm/5_BASELUXMMOMENT_2.jpg",
                    "assets/img/rolex/datejust fond vert 41mm/1_126300-green-jub-126300-0020-5-510x680.webp",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Milgauss Fond Bleu 116400GV/4_milgaussblue4.jpg',
                'alt' => 'Milgauss Fond Bleu 116400GV',
                'title' => 'Milgauss Fond Bleu 116400GV',
                'images' => [
                    "assets/img/rolex/Milgauss Fond Bleu 116400GV/4_milgaussblue4.jpg",
                    "assets/img/rolex/Milgauss Fond Bleu 116400GV/2_milgaussblue1.jpg",
                    "assets/img/rolex/Milgauss Fond Bleu 116400GV/1_milgaussblue2.jpg",
                    "assets/img/rolex/Milgauss Fond Bleu 116400GV/5_milgaussblue2.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Datejust Wimbledon 41/rolex-datejust-41-wimbledon-126334-4-scaled.jpg',
                'alt' => 'Datejust Wimbledon 41',
                'title' => 'Datejust Wimbledon 41',
                'images' => [
                    "assets/img/rolex/Datejust Wimbledon 41/rolex-datejust-41-wimbledon-126334-4-scaled.jpg",
                    "assets/img/rolex/Datejust Wimbledon 41/IMG_2982-scaled.jpg",
                    "assets/img/rolex/Datejust Wimbledon 41/IMG_0986.jpg",
                    "assets/img/rolex/Datejust Wimbledon 41/IMG_0988.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme/Rolex-GMT-Master-II-126710BLNR-Batman-Jubilee-Review-1.jpg',
                'alt' => 'GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme',
                'title' => 'GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme',
                'images' => [
                    "assets/img/rolex/GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme/Rolex-GMT-Master-II-126710BLNR-Batman-Jubilee-Review-1.jpg",
                    "assets/img/rolex/GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme/Untitleddesign_28.png",
                    "assets/img/rolex/GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme/batman-new.jpg",
                    "assets/img/rolex/GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme/rolex-gmt-master-ii-batman-batgirl-jubilee-mens-watch-126710blnr-0002-luxury-swiss-176.webp",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Rolex Sky-Dweller/35427216-h4bxdu4hp883znmr5pk5gjco-ExtraLarge.jpg',
                'alt' => 'Rolex Sky-Dweller',
                'title' => 'Rolex Sky-Dweller',
                'images' => [
                    "assets/img/rolex/Rolex Sky-Dweller/35427216-h4bxdu4hp883znmr5pk5gjco-ExtraLarge.jpg",
                    "assets/img/rolex/Rolex Sky-Dweller/OrangeSimpleIllustratiionOnlineShopLogo_6_19c1e6a2-3e2d-4e06-8197-c060566a99ab.jpg",
                    "assets/img/rolex/Rolex Sky-Dweller/35427216-9t3pcixfbxyv3x3omg762sno-ExtraLarge.jpg",
                    "assets/img/rolex/Rolex Sky-Dweller/35427216-tetk0e3do7gjpcanx039ljj2-ExtraLarge.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Rolex Datejust/d8807c521235d6a3363740073ff1c8ca.jpg',
                'alt' => 'Rolex Datejust',
                'title' => 'Rolex Datejust',
                'images' => [
                    "assets/img/rolex/Rolex Datejust/d8807c521235d6a3363740073ff1c8ca.jpg",
                    "assets/img/rolex/Rolex Datejust/BASELUXREF_11.jpg",
                    "assets/img/rolex/Rolex Datejust/28aefff68c26b70c824095f9e4a79fbd.jpg",
                    "assets/img/rolex/Rolex Datejust/2b475619815182f72be28e5d61860014.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Daytona Cosmographe Doré 116518LN/daytonagold9.jpg',
                'alt' => 'Daytona Cosmographe Doré 116518LN',
                'title' => 'Daytona Cosmographe Doré 116518LN',
                'images' => [
                    "assets/img/rolex/Daytona Cosmographe Doré 116518LN/daytonagold9.jpg",
                    "assets/img/rolex/Daytona Cosmographe Doré 116518LN/Lady_Dior_My_ABC_8.png",
                    "assets/img/rolex/Daytona Cosmographe Doré 116518LN/daytonagold.jpg",
                    "assets/img/rolex/Daytona Cosmographe Doré 116518LN/daytonagold8.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Rolex Submariner Noir/Untitleddesign_46.png',
                'alt' => 'Rolex Submariner Noir',
                'title' => 'Rolex Submariner Noir',
                'images' => [
                    "assets/img/rolex/Rolex Submariner Noir/Untitleddesign_46.png",
                    "assets/img/rolex/Rolex Submariner Noir/WhatsAppImage2020-10-06at14.42.56.jpg",
                    "assets/img/rolex/Rolex Submariner Noir/WhatsAppImage2020-10-06at14.42.58_1_1.jpg",
                    "assets/img/rolex/Rolex Submariner Noir/WhatsAppImage2020-10-06at14.42.58.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Rolex Day-Date 40/2_436470291_18020638049150134_885594530807949034_n.jpg',
                'alt' => 'Rolex Day-Date 40',
                'title' => 'Rolex Day-Date 40',
                'images' => [
                    "assets/img/rolex/Rolex Day-Date 40/2_436470291_18020638049150134_885594530807949034_n.jpg",
                    "assets/img/rolex/Rolex Day-Date 40/1_LadyDiorMyABC_10.png",
                    "assets/img/rolex/Rolex Day-Date 40/3_435480946_18020638040150134_5999913618993311055_n.jpg"
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Rolex Day-Date 40 gris/25941909-3kvnj3viske92fkhpzpddhte-ExtraLarge.jpg',
                'alt' => 'Rolex Day-Date 40 gris',
                'title' => 'Rolex Day-Date 40 gris',
                'images' => [
                    "assets/img/rolex/Rolex Day-Date 40 gris/25941909-3kvnj3viske92fkhpzpddhte-ExtraLarge.jpg",
                    "assets/img/rolex/Rolex Day-Date 40 gris/25941909-wusrh2d2bx4fovt8e5fx8a2u-ExtraLarge.jpg",
                    "assets/img/rolex/Rolex Day-Date 40 gris/25941909-81f358h4uxcqonjuewjigz0j-ExtraLarge.jpg",
                    "assets/img/rolex/Rolex Day-Date 40 gris/OrangeSimpleIllustratiionOnlineShopLogo_6.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme/ROLEXSUBMARINERLUNETTEVERTEMODELE16610LV5.jpg',
                'alt' => 'SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme',
                'title' => 'SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme',
                'images' => [
                    "assets/img/rolex/SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme/ROLEXSUBMARINERLUNETTEVERTEMODELE16610LV5.jpg",
                    "assets/img/rolex/SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme/ROLEXSUBMARINERLUNETTEVERTEMODELE16610LV6.jpg",
                    "assets/img/rolex/SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme/ROLEXSUBMARINERLUNETTEVERTEMODELE16610LV3.jpg",
                    "assets/img/rolex/SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme/4_a8953aa3-9545-4792-b935-dddb79569a19.png",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ]
        ];

        $brands = [
            [
                'image' => 'assets/img/rolex/18975-rolex-logo.png',
                'alt' => 'Rolex',
                'title' => 'Rolex',
                'video' => 'assets/img/rolex/videoplayback.mp4',
                'slug' => 'rolex',
            ],
            [
                'image' => 'assets/img/audemars/ Audemars Piguit Logo.png',
                'alt' => 'Audemars Piguit',
                'video' => 'assets/img/audemars/Royal Oak -  Audemars Piguet.mp4',
                'title' => 'Audemars Piguit',
                'slug' => 'audemars',
            ],
            [
                'image' => 'assets/img/patekphilippe/patek-philippe logo.png',
                'alt' => 'Patek Philippe',
                'title' => 'Patek Philippe',
                'video' => 'assets/img/patekphilippe/Patek Philippe four new Nautilus models.mp4',
                'slug' => 'patek',
            ],
            [
                'image' => 'assets/img/hublot/HUBLOT-LOGO.png',
                'alt' => 'Hublot',
                'title' => 'Hublot',
                'video' => 'assets/img/hublot/HUBLOT - CLASSIC FUSION ELEMENTS.mp4',
                'slug' => 'hublot',
            ],
            [
                'image' => 'assets/img/tissot/tissot-logo.png',
                'alt' => 'Tissot',
                'title' => 'Tissot',
                'video' => 'assets/img/tissot/Tissot PRX - Cinematic Ad.mp4',
                'slug' => 'tissot',
            ],
            [
                'image' => 'assets/img/cartier/cartier-2-logo.png',
                'alt' => 'Cartier',
                'title' => 'Cartier',
                'video' => 'assets/img/cartier/Cartier Watch Shape Your Time Official Video | aBlogtoWatch.mp4',
                'slug' => 'cartier',
            ],
            [
                'image' => 'assets/img/richardmille/6481a7ab9183c6fd9bba1b1a_Frame_76-removebg-preview.png',
                'alt' => 'richardmille',
                'title' => 'richardmille',
                'video' => 'assets/img/richardmille/RM 27-05 Flying Tourbillon Rafael Nadal — RICHARD MILLE.mp4',
                'slug' => 'richardmille',
            ],
        ];

        $watches = [
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris2.png',
                'alt' => 'Daytona Cosmographe gris 116518LN',
                'title' => 'Daytona Cosmographe gris 116518LN',
                'images' => [
                    "assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris2.png",
                    "assets/img/rolex/Daytona Cosmographe gris 116518LN/r13.jpg",
                    "assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris5.png",
                    "assets/img/rolex/Daytona Cosmographe gris 116518LN/daytonagris1.png",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/datejust fond vert 41mm/3_126300-green-jub-126300-0020-3-510x680.webp',
                'alt' => 'datejust fond vert 41mm',
                'title' => 'datejust fond vert 41mm',
                'images' => [
                    "assets/img/rolex/datejust fond vert 41mm/3_126300-green-jub-126300-0020-3-510x680.webp",
                    "assets/img/rolex/datejust fond vert 41mm/4_126300-green-jub-126300-0020-2-510x680.webp",
                    "assets/img/rolex/datejust fond vert 41mm/5_BASELUXMMOMENT_2.jpg",
                    "assets/img/rolex/datejust fond vert 41mm/1_126300-green-jub-126300-0020-5-510x680.webp",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Milgauss Fond Bleu 116400GV/4_milgaussblue4.jpg',
                'alt' => 'Milgauss Fond Bleu 116400GV',
                'title' => 'Milgauss Fond Bleu 116400GV',
                'images' => [
                    "assets/img/rolex/Milgauss Fond Bleu 116400GV/4_milgaussblue4.jpg",
                    "assets/img/rolex/Milgauss Fond Bleu 116400GV/2_milgaussblue1.jpg",
                    "assets/img/rolex/Milgauss Fond Bleu 116400GV/1_milgaussblue2.jpg",
                    "assets/img/rolex/Milgauss Fond Bleu 116400GV/5_milgaussblue2.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Datejust Wimbledon 41/rolex-datejust-41-wimbledon-126334-4-scaled.jpg',
                'alt' => 'Datejust Wimbledon 41',
                'title' => 'Datejust Wimbledon 41',
                'images' => [
                    "assets/img/rolex/Datejust Wimbledon 41/rolex-datejust-41-wimbledon-126334-4-scaled.jpg",
                    "assets/img/rolex/Datejust Wimbledon 41/IMG_2982-scaled.jpg",
                    "assets/img/rolex/Datejust Wimbledon 41/IMG_0986.jpg",
                    "assets/img/rolex/Datejust Wimbledon 41/IMG_0988.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme/Rolex-GMT-Master-II-126710BLNR-Batman-Jubilee-Review-1.jpg',
                'alt' => 'GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme',
                'title' => 'GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme',
                'images' => [
                    "assets/img/rolex/GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme/Rolex-GMT-Master-II-126710BLNR-Batman-Jubilee-Review-1.jpg",
                    "assets/img/rolex/GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme/Untitleddesign_28.png",
                    "assets/img/rolex/GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme/batman-new.jpg",
                    "assets/img/rolex/GMT-Master II _BATMAN_ 126710BLNR Jubilée Pour Homme/rolex-gmt-master-ii-batman-batgirl-jubilee-mens-watch-126710blnr-0002-luxury-swiss-176.webp",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Rolex Sky-Dweller/35427216-h4bxdu4hp883znmr5pk5gjco-ExtraLarge.jpg',
                'alt' => 'Rolex Sky-Dweller',
                'title' => 'Rolex Sky-Dweller',
                'images' => [
                    "assets/img/rolex/Rolex Sky-Dweller/35427216-h4bxdu4hp883znmr5pk5gjco-ExtraLarge.jpg",
                    "assets/img/rolex/Rolex Sky-Dweller/OrangeSimpleIllustratiionOnlineShopLogo_6_19c1e6a2-3e2d-4e06-8197-c060566a99ab.jpg",
                    "assets/img/rolex/Rolex Sky-Dweller/35427216-9t3pcixfbxyv3x3omg762sno-ExtraLarge.jpg",
                    "assets/img/rolex/Rolex Sky-Dweller/35427216-tetk0e3do7gjpcanx039ljj2-ExtraLarge.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Rolex Datejust/d8807c521235d6a3363740073ff1c8ca.jpg',
                'alt' => 'Rolex Datejust',
                'title' => 'Rolex Datejust',
                'images' => [
                    "assets/img/rolex/Rolex Datejust/d8807c521235d6a3363740073ff1c8ca.jpg",
                    "assets/img/rolex/Rolex Datejust/BASELUXREF_11.jpg",
                    "assets/img/rolex/Rolex Datejust/28aefff68c26b70c824095f9e4a79fbd.jpg",
                    "assets/img/rolex/Rolex Datejust/2b475619815182f72be28e5d61860014.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Daytona Cosmographe Doré 116518LN/daytonagold9.jpg',
                'alt' => 'Daytona Cosmographe Doré 116518LN',
                'title' => 'Daytona Cosmographe Doré 116518LN',
                'images' => [
                    "assets/img/rolex/Daytona Cosmographe Doré 116518LN/daytonagold9.jpg",
                    "assets/img/rolex/Daytona Cosmographe Doré 116518LN/Lady_Dior_My_ABC_8.png",
                    "assets/img/rolex/Daytona Cosmographe Doré 116518LN/daytonagold.jpg",
                    "assets/img/rolex/Daytona Cosmographe Doré 116518LN/daytonagold8.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Rolex Submariner Noir/Untitleddesign_46.png',
                'alt' => 'Rolex Submariner Noir',
                'title' => 'Rolex Submariner Noir',
                'images' => [
                    "assets/img/rolex/Rolex Submariner Noir/Untitleddesign_46.png",
                    "assets/img/rolex/Rolex Submariner Noir/WhatsAppImage2020-10-06at14.42.56.jpg",
                    "assets/img/rolex/Rolex Submariner Noir/WhatsAppImage2020-10-06at14.42.58_1_1.jpg",
                    "assets/img/rolex/Rolex Submariner Noir/WhatsAppImage2020-10-06at14.42.58.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Rolex Day-Date 40/2_436470291_18020638049150134_885594530807949034_n.jpg',
                'alt' => 'Rolex Day-Date 40',
                'title' => 'Rolex Day-Date 40',
                'images' => [
                    "assets/img/rolex/Rolex Day-Date 40/2_436470291_18020638049150134_885594530807949034_n.jpg",
                    "assets/img/rolex/Rolex Day-Date 40/1_LadyDiorMyABC_10.png",
                    "assets/img/rolex/Rolex Day-Date 40/3_435480946_18020638040150134_5999913618993311055_n.jpg"
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/Rolex Day-Date 40 gris/25941909-3kvnj3viske92fkhpzpddhte-ExtraLarge.jpg',
                'alt' => 'Rolex Day-Date 40 gris',
                'title' => 'Rolex Day-Date 40 gris',
                'images' => [
                    "assets/img/rolex/Rolex Day-Date 40 gris/25941909-3kvnj3viske92fkhpzpddhte-ExtraLarge.jpg",
                    "assets/img/rolex/Rolex Day-Date 40 gris/25941909-wusrh2d2bx4fovt8e5fx8a2u-ExtraLarge.jpg",
                    "assets/img/rolex/Rolex Day-Date 40 gris/25941909-81f358h4uxcqonjuewjigz0j-ExtraLarge.jpg",
                    "assets/img/rolex/Rolex Day-Date 40 gris/OrangeSimpleIllustratiionOnlineShopLogo_6.jpg",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ],
            [
                'tag' => 'Sale',
                'image' => 'assets/img/rolex/SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme/ROLEXSUBMARINERLUNETTEVERTEMODELE16610LV5.jpg',
                'alt' => 'SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme',
                'title' => 'SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme',
                'images' => [
                    "assets/img/rolex/SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme/ROLEXSUBMARINERLUNETTEVERTEMODELE16610LV5.jpg",
                    "assets/img/rolex/SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme/ROLEXSUBMARINERLUNETTEVERTEMODELE16610LV6.jpg",
                    "assets/img/rolex/SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme/ROLEXSUBMARINERLUNETTEVERTEMODELE16610LV3.jpg",
                    "assets/img/rolex/SUBMARINER LUNETTE VERTE MODÈLE 16610LV Pour Homme/4_a8953aa3-9545-4792-b935-dddb79569a19.png",
                ],
                'slug' => 'rolex',
                'brand_slug' => 'rolex',
                'price' => '750',
                'price_packaging' => '900',
            ]
        ];

        return view('Users.welcome', ['watches' => $watches, 'brands' => $brands, 'products' => $products, 'features' => $features, 'product' => $product]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}
